version: '3.8'

services:
  web:
    image: betting_image
    build:
      context: .
    container_name: betting_app
    env_file:
      - .env
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_HOST=betting_db
      - DB_BASENAME=betting
    depends_on:
      - db
    command: [ "/app/docker/app.sh" ]
    ports:
      - 8085:8000

  db:
    image: postgres:15
    container_name: betting_db
    volumes:
      - ./dumps/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=betting
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  dumps:
